### ISSUE TITLE
Some folks are having issues with device discoveries and updates

### ISSUE THREAD

**Issue by dwengrovitz** [dbarentine/udi-honeywellhome-poly#2] opened 2020-03-01 19:51 UTC
Hi @dbarentine ... at least a couple of folks are seeing issues with trying to get this node server working on a UDI Polisy device (see more at https://forum.universal-devices.com/topic/28877-honeywell-home-polyglot-cloud/).  Any thoughts or suggestions?

**Comment by dbarentine** [comment] 2020-03-02 08:12
Thanks @dwengrovitz I'll take a look as I hadn't seen that.

**Comment by dwengrovitz** [comment] 2020-03-02 23:27
Thanks @dbarentine.  Didn't mean to nag ... just wasn't sure if you had seen the posts.  Since I was one of the folks reporting a problem, please let me know If I can do anything to assist or provide more info.  Thanks again.

**Comment by dbarentine** [comment] 2020-03-03 01:07
@dwengrovitz no worries I hadn't seen the other thread and generally I'd prefer a bug gets logged here anyways.

I've updated the thread over at universal-devices but mainly what I need is temporary access to someone's Honeywell Home account so I can stick it in the debugger to find the issue. Otherwise tonight or tomorrow I will look at adding some logging to see if we can identify what the issue is.

**Comment by dbarentine** [comment] 2020-03-08 07:05
@dwengrovitz This should now be resolved with version 1.1.0 which should show up in the nodeserver store shortly.

**Closed by dbarentine** 2020-03-08 07:05 UTC
Labels: bug
